// Copyright (c) 2026 Scott W. Corley
// SPDX-License-Identifier: Apache-2.0

package emit_llvm_test

import (
	"strings"
	"testing"

	"github.com/scottcorleyg1/candor/compiler/emit_llvm"
	"github.com/scottcorleyg1/candor/compiler/lexer"
	"github.com/scottcorleyg1/candor/compiler/parser"
	"github.com/scottcorleyg1/candor/compiler/typeck"
)

func compileLL(t *testing.T, src string) string {
	t.Helper()
	tokens, err := lexer.Tokenize("test.cnd", src)
	if err != nil {
		t.Fatalf("lex: %v", err)
	}
	file, err := parser.Parse("test.cnd", tokens)
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	res, err := typeck.Check(file)
	if err != nil {
		t.Fatalf("typeck: %v", err)
	}
	out, err := emit_llvm.EmitLLVM(file, res)
	if err != nil {
		t.Fatalf("emit_llvm: %v", err)
	}
	return out
}

func assertContains(t *testing.T, haystack, needle string) {
	t.Helper()
	if !strings.Contains(haystack, needle) {
		t.Errorf("expected IR to contain %q\nGot:\n%s", needle, haystack)
	}
}

func TestEmitHeader(t *testing.T) {
	out := compileLL(t, `fn main() -> unit { return unit }`)
	assertContains(t, out, `; LLVM IR generated by Candor compiler`)
	assertContains(t, out, `target triple`)
}

func TestEmitMainWrapper(t *testing.T) {
	out := compileLL(t, `fn main() -> unit { return unit }`)
	assertContains(t, out, `define void @_cnd_main()`)
	assertContains(t, out, `define i32 @main()`)
	assertContains(t, out, `call void @_cnd_main()`)
	assertContains(t, out, `ret i32 0`)
}

func TestEmitReturnInt(t *testing.T) {
	out := compileLL(t, `fn add(a: i64, b: i64) -> i64 { return a + b }`)
	assertContains(t, out, `define i64 @add`)
	assertContains(t, out, `add i64`)
	assertContains(t, out, `ret i64`)
}

func TestEmitLetBinding(t *testing.T) {
	out := compileLL(t, `fn foo() -> i64 { let x: i64 = 42 return x }`)
	assertContains(t, out, `alloca i64`)
	assertContains(t, out, `store i64 42`)
	assertContains(t, out, `load i64`)
	assertContains(t, out, `ret i64`)
}

func TestEmitIfElse(t *testing.T) {
	out := compileLL(t, `fn abs(x: i64) -> i64 {
		if x < 0 { return -x } else { return x }
	}`)
	assertContains(t, out, `icmp slt i64`)
	assertContains(t, out, `br i1`)
	assertContains(t, out, `then.`)
	assertContains(t, out, `else.`)
}

func TestEmitWhile(t *testing.T) {
	out := compileLL(t, `fn countdown(n: i64) -> unit {
		let mut i: i64 = n
		while i > 0 { i = i - 1 }
	}`)
	assertContains(t, out, `while.hdr`)
	assertContains(t, out, `while.body`)
	assertContains(t, out, `while.exit`)
	assertContains(t, out, `icmp sgt i64`)
}

func TestEmitLoop(t *testing.T) {
	out := compileLL(t, `fn forever() -> unit {
		loop { break }
	}`)
	assertContains(t, out, `loop.body`)
	assertContains(t, out, `loop.exit`)
	assertContains(t, out, `br label %loop.exit`)
}

func TestEmitStringLiteral(t *testing.T) {
	out := compileLL(t, `fn greet() -> str { return "hello" }`)
	assertContains(t, out, `@.str.0`)
	assertContains(t, out, `constant`)
	assertContains(t, out, `hello`)
}

func TestEmitStruct(t *testing.T) {
	out := compileLL(t, `
struct Point { x: i64, y: i64 }
fn make_point(x: i64, y: i64) -> Point {
	return Point { x: x, y: y }
}
fn get_x(p: Point) -> i64 { return p.x }
`)
	assertContains(t, out, `%Point = type { i64, i64 }`)
	assertContains(t, out, `insertvalue %Point`)
	assertContains(t, out, `extractvalue %Point`)
}

func TestEmitExternDecl(t *testing.T) {
	out := compileLL(t, `
extern fn puts(s: str) -> i32
fn main() -> unit {
	puts("hi")
}
`)
	assertContains(t, out, `declare i32 @puts(ptr)`)
}

func TestEmitBoolOps(t *testing.T) {
	out := compileLL(t, `fn check(a: bool, b: bool) -> bool { return a and b }`)
	assertContains(t, out, `and i1`)
}

func TestEmitCast(t *testing.T) {
	out := compileLL(t, `fn to_f64(x: i64) -> f64 { return x as f64 }`)
	assertContains(t, out, `sitofp i64`)
	assertContains(t, out, `to double`)
}

func TestEmitEnum(t *testing.T) {
	out := compileLL(t, `
enum Color { Red, Green, Blue }
fn make_red() -> Color { return Color::Red }
`)
	assertContains(t, out, `%Color = type { i32 }`)
	assertContains(t, out, `insertvalue %Color zeroinitializer, i32 0`)
}

func TestEmitArithmeticOps(t *testing.T) {
	out := compileLL(t, `
fn ops(a: i64, b: i64) -> i64 {
	let x: i64 = a * b
	let y: i64 = x / 2
	let z: i64 = y % 3
	return z
}`)
	assertContains(t, out, `mul i64`)
	assertContains(t, out, `sdiv i64`)
	assertContains(t, out, `srem i64`)
}

func TestNoMainWrapper_WithoutMain(t *testing.T) {
	out := compileLL(t, `fn add(a: i64, b: i64) -> i64 { return a + b }`)
	if strings.Contains(out, `define i32 @main()`) {
		t.Errorf("should not emit i32 @main when no Candor main exists")
	}
}
