// Copyright (c) 2026 Scott W. Corley
// SPDX-License-Identifier: Apache-2.0

// Package manifest: lock file support (Candor.lock).
//
// Format (TOML-like, machine-written):
//
//	# Generated by candorc fetch. Do not edit manually.
//
//	[[package]]
//	name     = "mylib"
//	source   = "path:../mylib"
//	resolved = "/abs/path/to/mylib"
//
//	[[package]]
//	name     = "remote-pkg"
//	source   = "git:https://github.com/user/repo@v1.0.0"
//	resolved = "/home/user/.candor/pkg/remote-pkg/v1.0.0"
//	rev      = "abc123def456"
package manifest

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

const LockFileName = "Candor.lock"

// LockedPackage is one resolved dependency entry in Candor.lock.
type LockedPackage struct {
	Name     string // dep name as declared in [dependencies]
	Source   string // original source string from Candor.toml
	Resolved string // absolute path to the package directory on disk
	Rev      string // git commit SHA (empty for path deps)
}

// LockFile is the parsed contents of Candor.lock.
type LockFile struct {
	Packages []LockedPackage
}

// Find returns the LockedPackage for the given dep name, or nil if not found.
func (lf *LockFile) Find(name string) *LockedPackage {
	for i := range lf.Packages {
		if lf.Packages[i].Name == name {
			return &lf.Packages[i]
		}
	}
	return nil
}

// LoadLock reads Candor.lock from the given path. Returns an empty LockFile
// (no error) if the file does not exist yet.
func LoadLock(path string) (*LockFile, error) {
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return &LockFile{}, nil
	}
	if err != nil {
		return nil, err
	}
	defer f.Close()

	lf := &LockFile{}
	var cur *LockedPackage
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if line == "[[package]]" {
			lf.Packages = append(lf.Packages, LockedPackage{})
			cur = &lf.Packages[len(lf.Packages)-1]
			continue
		}
		if cur == nil {
			continue
		}
		eqIdx := strings.IndexByte(line, '=')
		if eqIdx < 0 {
			continue
		}
		key := strings.TrimSpace(line[:eqIdx])
		val := unquote(strings.TrimSpace(line[eqIdx+1:]))
		switch key {
		case "name":
			cur.Name = val
		case "source":
			cur.Source = val
		case "resolved":
			cur.Resolved = val
		case "rev":
			cur.Rev = val
		}
	}
	return lf, scanner.Err()
}

// WriteLock writes lf to path atomically (write to .tmp then rename).
func WriteLock(path string, lf *LockFile) error {
	tmp := path + ".tmp"
	f, err := os.Create(tmp)
	if err != nil {
		return err
	}
	w := bufio.NewWriter(f)
	fmt.Fprintln(w, "# Generated by candorc fetch. Do not edit manually.")
	for _, pkg := range lf.Packages {
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "[[package]]")
		fmt.Fprintf(w, "name     = %q\n", pkg.Name)
		fmt.Fprintf(w, "source   = %q\n", pkg.Source)
		fmt.Fprintf(w, "resolved = %q\n", pkg.Resolved)
		if pkg.Rev != "" {
			fmt.Fprintf(w, "rev      = %q\n", pkg.Rev)
		}
	}
	if err := w.Flush(); err != nil {
		f.Close()
		os.Remove(tmp)
		return err
	}
	if err := f.Close(); err != nil {
		os.Remove(tmp)
		return err
	}
	return os.Rename(tmp, path)
}

// LockPath returns the canonical Candor.lock path for a manifest directory.
func LockPath(manifestDir string) string {
	return filepath.Join(manifestDir, LockFileName)
}
